# the migration file is where you build your database tables
# If you create a new release for your extension ,
# remember the migration file is like a blockchain, never edit only add!

empty_dict: dict[str, str] = {}


async def m001_extension_settings(db):
    """
    Initial settings table.
    """

    await db.execute(
        f"""
        CREATE TABLE orders.extension_settings (
            id TEXT NOT NULL,
            npub TEXT,
            telegram TEXT,
            email TEXT,
            updated_at TIMESTAMP NOT NULL DEFAULT {db.timestamp_now}
        );
    """
    )


async def m002_orders(db):
    """
    Initial orders table.
    """

    await db.execute(
        f"""
        CREATE TABLE orders.orders (
            id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL,
            source TEXT NOT NULL,
            items TEXT NOT NULL DEFAULT '{empty_dict}',
            date TIMESTAMP NOT NULL,
            order_number INT NOT NULL,
            sales_rep_name TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT {db.timestamp_now},
            updated_at TIMESTAMP NOT NULL DEFAULT {db.timestamp_now}
        );
    """
    )


async def m003_not_needed(db):
    """
    Initial not needed table.
    """

    await db.execute(
        f"""
        CREATE TABLE orders.not_needed (
            id TEXT PRIMARY KEY,
            orders_id TEXT NOT NULL,
            ignore TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT {db.timestamp_now},
            updated_at TIMESTAMP NOT NULL DEFAULT {db.timestamp_now}
        );
    """
    )


async def m004_rebuild_orders(db):
    """
    Rebuild orders table to store TPoS order payloads.
    """

    await db.execute("ALTER TABLE orders.orders RENAME TO orders_old")
    await db.execute(
        f"""
        CREATE TABLE orders.orders (
            id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL,
            source TEXT NOT NULL,
            tpos_id TEXT,
            tpos_name TEXT,
            payment_hash TEXT NOT NULL,
            checking_id TEXT NOT NULL,
            amount_msat {db.big_int} NOT NULL,
            fee_msat {db.big_int} NOT NULL,
            memo TEXT,
            paid_in_fiat BOOLEAN NOT NULL DEFAULT false,
            currency TEXT,
            exchange_rate REAL,
            tax_included BOOLEAN,
            tax_value REAL,
            items TEXT NOT NULL DEFAULT '[]',
            notes TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT {db.timestamp_now},
            updated_at TIMESTAMP NOT NULL DEFAULT {db.timestamp_now}
        );
    """
    )
    rows = [list(row) for row in await db.fetchall("SELECT * FROM orders.orders_old")]
    for row in rows:
        await db.execute(
            """
            INSERT INTO orders.orders (
                id,
                user_id,
                source,
                tpos_id,
                tpos_name,
                payment_hash,
                checking_id,
                amount_msat,
                fee_msat,
                memo,
                paid_in_fiat,
                currency,
                exchange_rate,
                tax_included,
                tax_value,
                items,
                notes,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                row[0],
                row[1],
                row[2],
                None,
                None,
                row[0],
                row[0],
                0,
                0,
                None,
                False,
                None,
                None,
                None,
                None,
                row[3],
                None,
                row[7],
                row[8],
            ),
        )
    await db.execute("DROP TABLE orders.orders_old")


async def m005_drop_not_needed(db):
    """
    Drop not_needed table generated by extension builder.
    """

    await db.execute("DROP TABLE orders.not_needed")


async def m006_add_order_customer_fields(db):
    """
    Add customer and fulfillment fields to orders.
    """

    await db.execute("ALTER TABLE orders.orders ADD COLUMN address TEXT;")
    await db.execute("ALTER TABLE orders.orders ADD COLUMN email TEXT;")
    await db.execute("ALTER TABLE orders.orders ADD COLUMN phone TEXT;")
    await db.execute("ALTER TABLE orders.orders ADD COLUMN npub TEXT;")
    await db.execute("ALTER TABLE orders.orders ADD COLUMN paid BOOLEAN DEFAULT false;")
    await db.execute(
        "ALTER TABLE orders.orders ADD COLUMN shipped BOOLEAN DEFAULT false;"
    )


async def m007_add_settings_fields(db):
    """
    Add messaging and business fields to settings.
    """

    await db.execute(
        "ALTER TABLE orders.extension_settings ADD COLUMN message_order_received TEXT;"
    )
    await db.execute(
        "ALTER TABLE orders.extension_settings ADD COLUMN message_order_shipped TEXT;"
    )
    await db.execute(
        "ALTER TABLE orders.extension_settings ADD COLUMN business_name TEXT;"
    )
    await db.execute(
        "ALTER TABLE orders.extension_settings ADD COLUMN business_address TEXT;"
    )
